[package]
name = "piston2dExample"
version = "0.1.0"
authors = ["TheOpenDevProject <tkgs28@gmail.com>"]
[[bin]]
name = "Jumping-Man"

[dependencies]
piston = "0.13.0"
piston2d-graphics = "0.10.0"
pistoncore-glutin_window = "0.15.0"
piston2d-opengl_graphics = "0.14.0"
